### ISSUE TITLE
Passed msg does not have the configured property

### ISSUE THREAD

**Issue by ikarisan** [waldbaer/node-red-persistent-values#3]
Hi!

I did not manage to use your node. :(
My received payload is something like this:

`{
  "brightness":254,
  "brightness_l1":254,
[...]
  "state":"OFF",
  "state_l1":"OFF"
}`

I would like to store msg.payload.state and msg.payload.brightness to a file.
But every time I am geting 
`"Passed msg does not have the configured property 'payload.state'"` 
and 
`"Passed msg does not have the configured property 'payload.brightness'"`

This is what I configured to write the state:
![grafik](https://user-images.githubusercontent.com/14032966/219960143-e17a934a-8a27-4f2f-ad5e-a4ebe0cff326.png)

**Comment by waldbaer** [comment]
Hello @ikarisan 

Thanks for reporting this issue!
I never had the use-case to use "nested" message properties. Therefore I never stumbled over this issue.
In versions prio to 1.3.0 only a "non-nested" message properties are working for (e.g. `msg.state`).

I just published version 1.3.0 which should now support the expected behavior!
Please let me know if this fixes the issue for you.
